# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# dbus-launch 
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS";
then
	eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# Fcitx-Unikey
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
fcitx -d &

# Touchpad 
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &
xinpit set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" 0.45 &

# Fonts
xset +fp /usr/share/fonts
xset +fp /home/xmiah/.fonts
xset fp rehash

wal -R &
xrdb -load ~/.Xresources &
urxvtd -q -f -o
compton -b --backend glx --glx-no-rebind-pixmap -cCfFbG -I 0.05 -D 10 -r4 -l-6 -t-5 -o.99 --vsync opengl-swc & 
xsetroot -cursor_name left_ptr &
xset m 1/1

export DUNST_FONT='Artwiz Lemon 7'
export DUNST_SIZE='0x0-20+30'
dunst -fn "$DUNST_FONT" -geometry "$DUNST_SIZE" &

sxhkd -c ~/.config/2bwm/2bwmrc &
exec 2bwm

